importing

In [2]:
import numpy as np

In [14]:
# set precision
np.set_printoptions(precision = 2)

creating matrix

In [15]:
a = np.array([1,3,4])
print(a)
print(a.shape)
print(a.dtype)

[1 3 4]
(3,)
int32


In [3]:
b = np.array([[1,2,3],[4,5,6],[6,3,7]])
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [6 3 7]]
(3, 3)
2


In [17]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(c.shape)
print(c.ndim)

[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3, 2)
3


In [18]:
d = np.array([[[[1,2],[3,4]],[[3,2],[6,4]],[[7,8],[9,0]]]])
print(d)
print(d.shape)
print(d.ndim)

[[[[1 2]
   [3 4]]

  [[3 2]
   [6 4]]

  [[7 8]
   [9 0]]]]
(1, 3, 2, 2)
4


In [19]:
e = np.array([[[[[3,4],[3,5]],[[2,1],[4,7]]]]])
print(e)
print(e.shape)
print(e.ndim)

[[[[[3 4]
    [3 5]]

   [[2 1]
    [4 7]]]]]
(1, 1, 2, 2, 2)
5


- generate matrix
     - linear
          - gap based
          - element based
     - random

In [20]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [22]:
a = np.arange(-np.pi,np.pi,.25)
print(a)
a.size

[-3.14 -2.89 -2.64 -2.39 -2.14 -1.89 -1.64 -1.39 -1.14 -0.89 -0.64 -0.39
 -0.14  0.11  0.36  0.61  0.86  1.11  1.36  1.61  1.86  2.11  2.36  2.61
  2.86  3.11]


26

In [23]:
b = np.linspace(1,10,100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [24]:
b . reshape(25,4)  # 2d matrix

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [25]:
b.reshape(5,5,4)   # 3d matrix

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [26]:
print(np.random.rand(3,3))

[[0.53 0.05 0.14]
 [0.24 0.46 0.7 ]
 [0.78 0.14 0.05]]


In [29]:
print(np.random.randn(5,5))

[[ 1.09 -0.32  0.8  -1.52 -0.02]
 [-1.2  -0.04  1.46 -0.54 -0.76]
 [-0.49 -1.13  0.54 -0.24  0.62]
 [ 1.21  0.56  0.02  0.5  -0.91]
 [-1.09 -1.12  0.71  0.05 -0.14]]


In [27]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [30]:
print(np.random.randint(1,100,(5,8)))

[[99 70 88 21 47 49 65 74]
 [99 61 59 89 22 63 42  8]
 [67 14 17 54 55 34 38 55]
 [95 60 55 25  7 36 95 82]
 [ 4 32 73 40 94 33 83  9]]


In [31]:
x = np.random.randint(1,11,(3,3))
y = np.random.randint(1,11,(3,3))
print(x)
print(y)

[[10 10  3]
 [ 3  1  2]
 [ 2  4  2]]
[[ 4  9 10]
 [ 9  8  3]
 [ 4  2  1]]


In [32]:
x+y # element wise addition

array([[14, 19, 13],
       [12,  9,  5],
       [ 6,  6,  3]])

In [33]:
x-10

array([[ 0,  0, -7],
       [-7, -9, -8],
       [-8, -6, -8]])

In [34]:
x.dot(y)

array([[142, 176, 133],
       [ 29,  39,  35],
       [ 52,  54,  34]])

In [3]:
import numpy as np
x = np.random.randint(20,50,(6,6))
print(x)

[[37 36 45 36 39 24]
 [27 35 49 23 36 40]
 [30 48 25 43 39 31]
 [24 37 29 23 39 36]
 [29 31 43 31 49 40]
 [33 39 44 34 49 29]]


In [4]:
z = []
for i in x:
    for j in i:
        if j >30:
            z.append(j)
print(np.array(z))
# this is not the best way

[37 36 45 36 39 35 49 36 40 48 43 39 31 37 39 36 31 43 31 49 40 33 39 44
 34 49]


In [5]:
x>30  # filter

array([[ True,  True,  True,  True,  True, False],
       [False,  True,  True, False,  True,  True],
       [False,  True, False,  True,  True,  True],
       [False,  True, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False]])

In [6]:
print(x[x>30])  # boolean filtering

[37 36 45 36 39 35 49 36 40 48 43 39 31 37 39 36 31 43 31 49 40 33 39 44
 34 49]


In [7]:
f = x<40
x[f]

array([37, 36, 36, 39, 24, 27, 35, 23, 36, 30, 25, 39, 31, 24, 37, 29, 23,
       39, 36, 29, 31, 31, 33, 39, 34, 29])

In [8]:
x[(x>30)&(x<45)]

array([37, 36, 36, 39, 35, 36, 40, 43, 39, 31, 37, 39, 36, 31, 43, 31, 40,
       33, 39, 44, 34])

In [9]:
f1 = x > 30
f2 = x < 45
x[f1 & f2]

array([37, 36, 36, 39, 35, 36, 40, 43, 39, 31, 37, 39, 36, 31, 43, 31, 40,
       33, 39, 44, 34])

Slicing

1D = [start : stop : step]

2D = [r_start : r_step , c_start:c_stop:c_step]


In [10]:
print('first row')
print(x[0])

first row
[37 36 45 36 39 24]


In [11]:
print('last row')
print(x[-1])

last row
[33 39 44 34 49 29]


In [12]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[30 48 25 43 39 31]
 [24 37 29 23 39 36]
 [29 31 43 31 49 40]
 [33 39 44 34 49 29]]


In [13]:
x[:,0]

array([37, 27, 30, 24, 29, 33])

In [14]:
 # select first 3 columns
x[:,:3]

array([[37, 36, 45],
       [27, 35, 49],
       [30, 48, 25],
       [24, 37, 29],
       [29, 31, 43],
       [33, 39, 44]])

In [15]:
x[:,-3:] # select last 3 columns

array([[36, 39, 24],
       [23, 36, 40],
       [43, 39, 31],
       [23, 39, 36],
       [31, 49, 40],
       [34, 49, 29]])